### ISSUE TITLE
Text file reader functionality

### ISSUE THREAD

**Issue by jholub15** [BodyViz/bump#7]
Implement basic text file reading capabilities. Allow users to ask for the entire file, first few lines, or any combination of. The user would be returned a bump::String or bump::StringList with each bump::String representing a single line of the file being read.

Lots of decisions left to be made on this including whether to use static methods and how best to return the results of the file.

**Comment by cnoon** [comment]
This is really good guys. I really like the idea. Let's definitely get it into Bump. Here's a good way to proceed.
- Move the class to a namespace with all public functions
- Implement the readFileLines() method in the implementation, not in the header so it's hidden
- Fully static classes should be written as namespaces instead of classes (see Environment or FileSystem)
- I don't have a problem with creating these big StringLists on the heap, but it's probably faster on the stack. I'd rather see the methods returning StringLists done that way if it is actually faster.
- Pass in all your variables by const ref

``` cpp
// Change this
static boost::shared_ptr<bump::StringList> returnFileContents(const bump::String fileName);

// To this
bump::StringList fileContents(const bump::String& filepath);

// Or this if faster
boost::shared_ptr<bump::StringList> fileContents(const bump::String& filepath);
```
- Refactor the methods so they are more verbose and don't start with "return" or "get"
  - Bump uses the setValue() and value() syntax for accessor type methods which is what these are
- Change up the documentation to be Doxygen friendly, many examples in the other classes
- Write up a full coverage unit test for all these methods to make sure they work properly
- To read the file, you'll have to create a temp one, stuff your text in it, then read it's filepath in the unit tests, then delete it when the test completes
  - If you need any help figuring that part of it out let me know

Go ahead and make all your changes in your fork of the repository. Be sure to pull down the latest version of it before you start making changes just so it's easier. If you throw it in your own branch and push it up, then you can submit a merge request to me and I can add your fork as a new remote and pull it down. Then once it's good to go, I'll merge it into the development branch. Just let me know if you have any questions or anything.

**Comment by cnoon** [comment]
Closing out this ticket since the changes have been merged into the development branch.
